// auth routes
// signup - create user

POST http://localhost:5000/api/v1/auth 
Content-Type: application/json

{
    "username": "system",
    "email": "system@email.com",
    "password": "password"
}

###
// signin - login user

POST http://localhost:5000/api/v1/auth/signin 
Content-Type: application/json

{
    "email": "kalidass@email.com",
    "password": "password"
}


###
// signout - logout user
POST http://localhost:5000/api/v1/auth/signout 


###
// user routes
// get all users
GET http://localhost:5000/api/v1/users


###
// get current user profile
GET http://localhost:5000/api/v1/users/profile

###
// update current user profile
PUT http://localhost:5000/api/v1/users/profile
Content-Type: application/json

{
    "username": "computer",
    "email": "computer@email.com",
    "password": "computer123"
}


###

// genre routes
// create genre
POST http://localhost:5000/api/v1/genre
Content-Type: application/json

{
    "name": "Adventure"
}

###

// update genre
PUT http://localhost:5000/api/v1/genre/6733384fbb300f720fc3f4da
Content-Type: application/json

{
    "name": "Sci-Fi"
}

###

// delete genre
DELETE http://localhost:5000/api/v1/genre/6733384fbb300f720fc3f4dam


###
// get all genres
GET http://localhost:5000/api/v1/genre/genres

###
// read specific genre
GET http://localhost:5000/api/v1/genre/6734a4541351765dced159a6

###
// movie routes
// create movie
POST http://localhost:5000/api/v1/movies
Content-Type: application/json

{
    "name": "Honey I blew up the kid",
    "image": "./image.png",
    "year": 2004,
    "genre": "6734a799a06ddcfbc38db915",
    "detail": "Best movie",
    "cast": ["Daniel", "Emma", "Rupert"]
}


###
// get all movies
GET http://localhost:5000/api/v1/movies

###
// get specific movie
GET http://localhost:5000/api/v1/movies/673752e379c52a93a90ab531

###
// update movie
PUT http://localhost:5000/api/v1/movies/67378065792a2d925643bd9a
Content-Type: application/json

{
    "name": "John Wick 2"
}


###
// add review
POST http://localhost:5000/api/v1/movies/673863aa1b8e99977515c4ac/review
Content-Type: application/json

{
    "rating": 5,
    "comment": "Best movie"
}

###
// delete movie
DELETE http://localhost:5000/api/v1/movies/6737803f792a2d925643bd94

###
// delete review
DELETE http://localhost:5000/api/v1/movies/67378065792a2d925643bd9a/review 
Content-Type: application/json

{
    "reviewId": "673848dbf12ee79fe47f15d8"
}

###
// get new movies
GET http://localhost:5000/api/v1/movies/new

###
// get rop rated movies
GET http://localhost:5000/api/v1/movies/top-rated

###
// get random movies
GET http://localhost:5000/api/v1/movies/random
