// auth routes
// signup - create user

POST http://localhost:5000/api/v1/auth 
Content-Type: application/json

{
    "username": "system",
    "email": "system@email.com",
    "password": "password"
}

###
// signin - login user

POST http://localhost:5000/api/v1/auth/signin 
Content-Type: application/json

{
    "email": "system@email.com",
    "password": "password"
}


###
// signout - logout user
POST http://localhost:5000/api/v1/auth/signout 


###
// user routes
// get all users
GET http://localhost:5000/api/v1/users


###
// get current user profile
GET http://localhost:5000/api/v1/users/profile

###
// update current user profile
PUT http://localhost:5000/api/v1/users/profile
Content-Type: application/json

{
    "username": "computer",
    "email": "computer@email.com",
    "password": "computer123"
}